name: Build and Deploy the App

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      runner:
        required: true
        type: string
      dist-id:
        required: true
        type: string
      bucket-region:
        required: true
        type: string
      bucket-name:
        required: true
        type: string

jobs:
  deploy:
    name: Deploying app
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Library's
        run: npm ci
      
      - name: Make Build
        run: npm run build
        env: 
          URL_ENV: ${{ inputs.env }}
          HIDDEN_CURRENT_VERSION: true

      - name: S3 upload
        uses: reggionick/s3-deploy@v3
        with:
          folder: build
          bucket: ${{ inputs.bucket-name }}
          bucket-region: ${{ inputs.bucket-region }}
          dist-id: ${{ inputs.dist-id }}
          invalidation: /
          delete-removed: false
          no-cache: true
          private: true
