name: Test deployment

on:
  push:
    branches:
      - release*
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  prepare:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Get version from branch name
        id: version
        run: echo "::set-output name=branch_version::$(echo $GITHUB_REF | sed 's/refs\/heads\/release-//g' )"
        shell: bash

      - name: Remove Versioning 
        continue-on-error: true
        run: npm run delete-version ${{ env.VERSION }}
        env:
            VERSION: ${{ steps.version.outputs.branch_version }}
        
      - name: Create Version
        run: npm run create-version $VERSION
        env:
            VERSION: ${{ steps.version.outputs.branch_version }}
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: '[Update] Version ${{ env.VERSION }} 🚀'
          push_options: '--force'
        env:
            VERSION: ${{ steps.version.outputs.branch_version }}

      - name: Sync branches
        uses: TreTuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: $GITHUB_REF
          TO_BRANCH: "qa"
        
      # - name: Test build website
      #   run: npm run build