name: Update Versioning branch

on:
  push:
    branches: 
      - 'release-v*'
 
jobs:
  deploy:
    name: Update Versioning Branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Setup Node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18'

      # - name: Install Librarys
      #   run: npm ci


      - name: Get version from branch name
        id: version
        run: echo "::set-output name=branch_version::$(echo $GITHUB_REF | sed 's/refs\/heads\/release-//g' )"
        shell: bash
      
      - name: Remove Versioning 
        run: touch versions3.json

      # - name: Create Version
      #   run: npm run docusaurus docs:version $VERSION
      #   env:
      #       VERSION: ${{ steps.version.outputs.branch_version }}
    
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: generate version ${{ steps.version.outputs.branch_version }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: true
          delete-branch: true
          branch: update-release-v1.0.0
          add-paths: |
            *
          title: '[BOT UPDATE] Update Version ${{ steps.version.outputs.branch_version }}'
          body: |
            Update release
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          draft: true