name: Update Versioning branch

on:
  push:
    branches: 
      - 'release-v*'
 
jobs:
  build:
    name: Update Versioning Branch
    runs-on: ubuntu-latest
    steps:
      - name: Get version from branch name
        id: version
        run: echo "::set-output name=branch_version::$(echo $GITHUB_REF | sed 's/refs\/heads\/release-//g' )"
        shell: bash
      

      - name: Create release branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          VERSION: ${{ steps.version.outputs.branch_version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "auto-update-release-${{ env.VERSION }}"

      - uses: actions/checkout@v3
        env:
          VERSION: ${{ steps.version.outputs.branch_version }}
        with:
          ref: auto-update-release-${{ env.VERSION }}
        
      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1
        
      - run: |
            touch versioned.txt
            git config user.name ${{ env.GIT_COMMIT_COMMITTER_NAME }}
            git config user.email ${{ env.GIT_COMMIT_COMMITTER_EMAIL }}
            git add .
            git commit -m "Generated Version"
            git status
            git push

      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.4.0
        env:
          VERSION: ${{ steps.version.outputs.branch_version }}
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "auto-update-release-${{ env.VERSION }}"
          TO_BRANCH: "qa"

      # - name: Create Version
      #   run: npm run docusaurus docs:version $VERSION
      #   env:
      #       VERSION: ${{ steps.version.outputs.branch_version }}
      


      # - name: Create Pull Request
      #   id: cpr
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     commit-message: generate version ${{ steps.version.outputs.branch_version }}
      #     committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
      #     author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
      #     signoff: true
      #     delete-branch: true
      #     branch: "auto-update-version"
      #     base: qa
      #     add-paths: |
      #       *
      #     title: '[BOT UPDATE] Update Version ${{ steps.version.outputs.branch_version }}'
      #     body: |
      #       Update release
      #       - Auto-generated by [create-pull-request][1]
      #       [1]: https://github.com/peter-evans/create-pull-request
      #     draft: false

      